pluginManagement {
    String fabricMavenUrl = System.getenv("FABRIC_MAVEN_URL") ?: "https://maven.fabricmc.net/"
    String centralMavenUrl = System.getenv("MAVEN_CENTRAL_URL") ?: "https://repo.maven.apache.org/maven2/"
    String pluginMavenUrl = System.getenv("GRADLE_PLUGIN_MAVEN_URL") ?: "https://plugins.gradle.org/m2/"

    repositories {
        maven { url = fabricMavenUrl }
        maven { url = centralMavenUrl }
        maven { url = pluginMavenUrl }
    }
}

rootProject.name = 'functional-slabs'
